# row, column文件使用注意
|英文名稱|臺灣|大陸|
|:-:|:-:|:-:|
|row|列|行|
|column|行|列|


> 先列row後行column <br>
> axis = 0 沿row方向(樣本數幾個)<br>
> axis = 1 沿column方向(幾個特徵)<br>

# one axis
[1,3,5]  #三個元素(three elements),長度為3(lenth is three)

# two axes 
axis = 0 -> 2  The first axis has a length of 2 <br>
axis = 1 -> 3  The second axis has a lenght of 3 <br>
[[1,3,5],   
 [2,4,6]]

In [2]:
import numpy as np

x = np.arange(3) # x=[0 1 2]
print(x)
print(type(x)) # output <class 'numpy.ndarray'>
# ndarry 可以多維但同值大小，同個Type
# array 只能有一維
# check x is np.ndarray or not
isinstance(x,np.ndarray) # True
# be float64 type
y = np.arange(3,dtype='float64') # y=[0. 1. 2.]
print(y)

# create list to transfer to np array
use_list = [1,2,3,4,5,6,7,8,9]
np_use_list = np.array(use_list)
print(np_use_list)

[0 1 2]
<class 'numpy.ndarray'>
[0. 1. 2.]
[1 2 3 4 5 6 7 8 9]


In [18]:
# np.zeros
x = np.arange(12) #[0 1 2 3 4 5 6 7 8 9 10 11]
x = np.arange(12).reshape(3,4) 
# [[0 1  2  3]   -> axis = 0 ->3
#  [4 5  6  7]   -> axis = 1 ->4
#  [8 9 10 11]]  -> x.shape = (3,4) 先列後行
print(x)
y = x.shape[1] # 取x.shape tuple的第二個數值
z = np.zeros(y+1)
print(z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0. 0. 0. 0. 0.]


In [5]:
# np.where(condition,x,y)
# 滿足條件conditon輸出x,不滿足輸出y
a = np.arange(10) 
print("原始",a)
a = np.where(a>5,1,0)
print("條件",a)

原始 [0 1 2 3 4 5 6 7 8 9]
條件 [0 0 0 0 0 0 1 1 1 1]


In [9]:
import numpy as np
x=[1,2,3,4,5]
y=[6,7,8,9,10]
x1,x2 = np.meshgrid(np.arange(1,6,1),np.arange(6,11,1))
x1.ravel()

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [10]:
x2.ravel()

array([ 6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,
        9,  9,  9, 10, 10, 10, 10, 10])